Repository EUCPilots/evergreen-module, pull requests merged in 2022-09, with the labels that each got.

#373 Development
  .vscode/PSScriptAnalyzerSettings.psd1
  .vscode/settings.json
  Evergreen/Apps/Get-MicrosoftTeams.ps1
  Evergreen/Apps/Get-PDFForgePDFCreator.ps1
  Evergreen/Apps/Get-VMwareTools.ps1
  Evergreen/Manifests/PDFForgePDFCreator.json
  Evergreen/Public/Get-EvergreenApp.ps1
  Evergreen/Public/Save-EvergreenApp.ps1
  ci/Variables.md
  docs/changelog.md
  tests/CodeCoverage.xml
  tests/TestResults.xml
Labels: enhancement

#376 Development
  Evergreen/Apps/Get-MicrosoftOneDrive.ps1
  Evergreen/Apps/Get-MozillaGeckoDriver.ps1
  Evergreen/Apps/Get-TrackerSoftwarePDFXChangeEditor.ps1
  Evergreen/Manifests/MicrosoftTeams.json
  Evergreen/Manifests/MozillaGeckoDriver.json
  Evergreen/Manifests/TrackerSoftwarePDFXChangeEditor.json
  Evergreen/Private/Invoke-WebRequestWrapper.ps1
  Evergreen/Public/Export-EvergreenApp.ps1
  Evergreen/Public/Get-EvergreenApp.ps1
  Evergreen/Public/Save-EvergreenApp.ps1
  ci/Variables.md
  docs/changelog.md
  tests/CodeCoverage.xml
  tests/TestResults.xml
Labels: enhancement, new application

#379 Hotfix for Connection Experience Indicator
  Evergreen/Manifests/ConnectionExperienceIndicator.json
Labels: new application

#378 Add Notepad3
  Evergreen/Apps/Get-RizonesoftNotepad3.ps1
  Evergreen/Manifests/RizonesoftNotepad3.json
Labels: new application
