Repository EUCPilots/evergreen-module, pull requests merged in 2023-07, with the labels that each got.

#515 Adds LehrerOffice
  Evergreen/Apps/Get-LehrerOffice.ps1
  Evergreen/Manifests/LehrerOffice.json
Labels: new application

#513 Add GeoGebra Classic
  Evergreen/Apps/Get-GeoGebraClassic.ps1
  Evergreen/Manifests/GeoGebraClassic.json
Labels: new application

#516 Fixing MS Visual Studio Code Update
  Evergreen/Apps/Get-MicrosoftVisualStudioCode.ps1
  Evergreen/Manifests/MicrosoftVisualStudioCode.json
Labels: bug

#517 Changing the jq lang project uri
  Evergreen/Manifests/jq.json
Labels: bug

#520 Development
  Disabled/CitrixVMTools.json
  Disabled/Get-CitrixVMTools.ps1
  Evergreen/Apps/Get-GeoGebraClassic.ps1
  Evergreen/Apps/Get-LehrerOffice.ps1
  Evergreen/Apps/Get-MicrosoftVisualStudioCode.ps1
  Evergreen/Apps/Get-Minitab.ps1
  Evergreen/Apps/Get-NodeJs.ps1
  Evergreen/Apps/Get-TPGiColourContrastAnalyser.ps1
  Evergreen/Apps/Get-ThymioSuite.ps1
  Evergreen/Manifests/GeoGebraClassic.json
  Evergreen/Manifests/LehrerOffice.json
  Evergreen/Manifests/MicrosoftVisualStudioCode.json
  Evergreen/Manifests/NodeJs.json
  Evergreen/Manifests/TPGiColourContrastAnalyser.json
  Evergreen/Manifests/ThymioSuite.json
  Evergreen/Manifests/jq.json
  Evergreen/Private/Get-GitHubRateLimit.ps1
  Evergreen/Private/Get-GitHubRepoRelease.ps1
  Evergreen/Public/Get-EvergreenApp.ps1
  docs/changelog.md
  tests/Private/Get-GitHubRateLimit.Tests.ps1
Labels: bug, enhancement, new application

#522 #521 Fix -AppParams
  Evergreen/Public/Get-EvergreenApp.ps1
  docs/changelog.md
Labels: bug
