Repository EUCPilots/evergreen-module, pull requests merged in 2023-03, with the labels that each got.

#467 Development
  Evergreen/Apps/Get-AWSCLI.ps1
  Evergreen/Apps/Get-ESETEndpointAntivirus.ps1
  Evergreen/Apps/Get-ESETEndpointSecurity.ps1
  Evergreen/Apps/Get-ESETFullDiskEncryption.ps1
  Evergreen/Apps/Get-ESETInspectConnector.ps1
  Evergreen/Apps/Get-ESETPROTECTServer.ps1
  Evergreen/Apps/Get-ESETSecureAuthentication.ps1
  Evergreen/Apps/Get-ESETServerSecurity.ps1
  Evergreen/Apps/Get-ResponsivelyApp.ps1
  Evergreen/Apps/Get-VMwareHorizonClient.ps1
  Evergreen/Manifests/AWSCLI.json
  Evergreen/Manifests/MicrosoftOutlook.json
  Evergreen/Manifests/OctopusTentacle.json
  Evergreen/Manifests/ResponsivelyApp.json
  Evergreen/Manifests/VMwareHorizonClient.json
  Evergreen/Public/Export-EvergreenApp.ps1
  docs/changelog.md
  tests/Public/Invoke-EvergreenApp.Tests.ps1
Labels: bug, enhancement, new application

#470 Update VMwareWorkstationPlayer.json
  Evergreen/Manifests/VMwareWorkstationPlayer.json
Labels: bug

#475 Development
  Evergreen/Apps/Get-AutodeskFusion360.ps1
  Evergreen/Apps/Get-ESETEndpointSecurity.ps1
  Evergreen/Apps/Get-GoToConnect.ps1
  Evergreen/Apps/Get-GoToMeeting.ps1
  Evergreen/Apps/Get-GoToOpener.ps1
  Evergreen/Apps/Get-MicrosoftAzurePipelinesAgent.ps1
  Evergreen/Apps/Get-PDFArranger.ps1
  Evergreen/Evergreen.psd1
  Evergreen/Manifests/AutodeskFusion360.json
  Evergreen/Manifests/GoToConnect.json
  Evergreen/Manifests/GoToMeeting.json
  Evergreen/Manifests/GoToOpener.json
  Evergreen/Manifests/MicrosoftAzurePipelinesAgent.json
  Evergreen/Manifests/PDFArranger.json
  Evergreen/Manifests/VMwareWorkstationPlayer.json
  Evergreen/Manifests/VMwareWorkstationPro.json
  docs/changelog.md
Labels: bug, enhancement
