Repository EUCPilots/evergreen-module, pull requests merged in 2024-09, with the labels that each got.

#738 Updated MattermostDesktop - changed download URL
  Evergreen/Manifests/MattermostDesktop.json
Labels: bug

#739 Apps
  Evergreen/Apps/Get-7Zip.ps1
  Evergreen/Apps/Get-AdvancedInstaller.ps1
  Evergreen/Manifests/7Zip.json
  Evergreen/Manifests/7zip.json
  Evergreen/Manifests/TechSmithCamtasia.json
  Evergreen/Manifests/TechSmithSnagit.json
Labels: bug, enhancement

#745 Apps
  Evergreen/Apps/Get-NetPad.ps1
  Evergreen/Manifests/MestrelabMnova.json
  Evergreen/Manifests/NetPad.json
Labels: new application

#746 Development
  Evergreen/Apps/Get-AWSCLI.ps1
  Evergreen/Apps/Get-Npcap.ps1
  Evergreen/Evergreen.json
  Evergreen/Evergreen.psd1
  Evergreen/Manifests/Npcap.json
  Evergreen/Private/Convert-Segment.ps1
  Evergreen/Public/ConvertTo-DotNetVersionClass.ps1
  Evergreen/Shared/Get-GitHubRepoRelease.ps1
  Evergreen/Shared/Get-GitHubRepoTag.ps1
  Evergreen/en-US/Evergreen-help.xml
  docs/help/en-US/ConvertTo-DotNetVersionClass.md
  docs/help/en-US/Export-EvergreenApp.md
  docs/help/en-US/Export-EvergreenManifest.md
  docs/help/en-US/Find-EvergreenApp.md
  docs/help/en-US/Get-EvergreenApp.md
  docs/help/en-US/Get-EvergreenAppFromApi.md
  docs/help/en-US/Get-EvergreenEndpointFromApi.md
  docs/help/en-US/Get-EvergreenLibrary.md
  docs/help/en-US/Get-EvergreenLibraryApp.md
  docs/help/en-US/New-EvergreenLibrary.md
  docs/help/en-US/Save-EvergreenApp.md
  docs/help/en-US/Start-EvergreenLibraryUpdate.md
  docs/help/en-US/Test-EvergreenApp.md
  tests/Public/ConvertTo-DotNetVersionClass.Tests.ps1
Labels: enhancement

#748 Apps
  Evergreen/Apps/Get-MicrosoftWindowsApp.ps1
  Evergreen/Manifests/MicrosoftWindowsApp.json
  docs/api.md
  docs/getlibraryapp.md
  docs/help/en-US/Get-EvergreenAppFromLibrary.md
  docs/index.md
  docs/under.md
  docs/updatelibrary.md
  docs/why.md
  mkdocs.yml
Labels: enhancement, new application
